@baseUrl = http://localhost:5044

### 1. Criar pessoa MENOR de idade (para os testes de regra)
POST {{baseUrl}}/Pessoas
Content-Type: application/json

{
  "nome": "Menor Teste",
  "idade": 15
}

### 2. Criar pessoa MAIOR de idade
POST {{baseUrl}}/Pessoas
Content-Type: application/json

{
  "nome": "Maior Teste",
  "idade": 30
}

### 3. Listar transações
GET {{baseUrl}}/Transacoes

### 4. Transação para pessoa INEXISTENTE (espera 404)
POST {{baseUrl}}/Transacoes
Content-Type: application/json

{
  "descricao": "Teste fantasma",
  "valor": 100.00,
  "tipo": "Despesa",
  "pessoaId": 999
}

### 5. RECEITA para MENOR de idade (espera 400)
POST {{baseUrl}}/Transacoes
Content-Type: application/json

{
  "descricao": "Mesada",
  "valor": 50.00,
  "tipo": "Receita",
  "pessoaId": 2
}

### 6. DESPESA para MENOR de idade (espera 201)
POST {{baseUrl}}/Transacoes
Content-Type: application/json

{
  "descricao": "Lanche",
  "valor": 20.00,
  "tipo": "Despesa",
  "pessoaId": 2
}